version: '3.9'
services:
  cfx:
    platform: linux/amd64
    build: .
    ports:
      - '40120:40120'
      - '30120:30120'
      - '30120:30120/udp'
    volumes:
      - './data:/server/txData'
    restart: 'on-failure'
  mariadb:
    image: mariadb:latest
    volumes:
      - './database:/var/lib/mysql'
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    restart: 'on-failure'
